server {
    listen 6110;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /console/;
    }

    location = /console {
        return 302 /console/;
    }

    location /console/ {
        try_files $uri $uri/ /console/index.html;
    }
}
